### ISSUE TITLE
Use PdfReader instead.

### ISSUE THREAD

**Issue by JaGuzmanT** [muratali016/Document-ChatGPT#1]
Hi there, excellent application of Chatgpt3. 
I had the following issue
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
I solved it using this:
pip install PyPDF2<3.0

Note: Using Python 3.9.9 on the windows version

**Comment by muratali016** [comment]
Yes, I've also faced that issue when I'm using the code in Colab, however, I'm using pdf version >3, and doesn't give me any errors in my local
If you want I can add your note to the readme @JaGuzmanT

**Comment by muratali016** [comment]
I think the issue is solved
