### ISSUE TITLE
pyperclip import module fails

### ISSUE THREAD

**Issue by nsbuttar** [muratali016/Document-ChatGPT#3]
Hi Thanks for the code. 

It appears that the pyperclip import module not available. Are you able to advise on another package? I'll have a look around

**Comment by nsbuttar** [comment]
actually could this because of the python 3.11 being unstable? 

e>
    import pyperclip  # Use pyperclip instead
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyperclip'

**Comment by muratali016** [comment]
It's not available for 3.11. I was working with 3.9 Python whilst creating the project. Check the compatible versions: https://pypi.org/project/pyperclip/

**Comment by nsbuttar** [comment]
Thanks mate. Nice work too!
