### ISSUE TITLE
ValueError: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead.

### ISSUE THREAD

**Issue by MArevaloSA** [muratali016/Document-ChatGPT#4]
Hi, I was trying to use this project, but when I was running `document_based_chatgpt.py`  the next error was showed: 
`ValueError: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use "from_documents" instead.`  I think it is because `llama-index`  version I installed `0.5.23.post1`. 
So I would like to open a PR to solved that.

**Comment by muratali016** [comment]
Can you detail the problem, on what line you have faced this and did you try to use what the error says
