### ISSUE TITLE
Increase the reading capacity of GPT Text Summarizer

### ISSUE THREAD

**Issue by thvi** [muratali016/Document-ChatGPT#5]
Increase the reading capacity of GPT Text Summarizer as in this Youtube video "GPT-3: How to summarize a PDF (70,000+ words) 📔" https://www.youtube.com/watch?v=AZDVvVYiHfg&t=2s

**Comment by muratali016** [comment]
@thvi I've created another project with the same logic please check out the project:https://github.com/muratali016/Youtube_AI_Detective
And I don't think that's a good idea to create text chunks to feed chatgpt, We need more upgrades from OpenAI

**Comment by thvi** [comment]
Okay, but your Youtube AI Detective project is not about summarizing a PDF with long text.

**Comment by muratali016** [comment]
@thvi Yes, but we can use the same method for PDFs
