### ISSUE TITLE
Are you using only the first 300 words of the input text to generate the summary?

### ISSUE THREAD

**Issue by aosmani-cedience** [muratali016/Document-ChatGPT#6]
Great work on this repo! I had a question:
Are you using only the first 300 words of the input text to generate the summary?
Is there any plan to incorporate the full text of the PDF?

**Comment by muratali016** [comment]
@kperumal-bts Hi thanks, I've created another project that can summarize the text regardless of the length of the content, I'm splitting the text into chunks and feeding the chatgpt, however, I still think that's not a good idea. That would be much better if gpt had a bigger content length itself. Please check my other project: on line 122 https://github.com/muratali016/Youtube_AI_Detective

**Comment by aosmani-cedience** [comment]
Ok, thanks!
